name: local_life_app
description: Local Message And Service App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0-prev2
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.25.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.2
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.7.3
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.7
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.0.2
#  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.5.1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0
  # Json转Model https://pub.flutter-io.cn/packages/json_serializable
  json_annotation: ^3.0.1
  # 刷新框架 https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.1.7
  encrypt: ^3.2.0
  gzx_dropdown_menu: ^2.1.0
  #evenBus
  event_bus: ^2.0.0
  # 权限管理框架 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^6.1.1
  # 获取手机信息 https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.0
  # 获取软件版本信息 https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.0
  # 屏幕适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0+2
  flutter_jpush: ^0.0.4
  scrollable_positioned_list: ^0.1.10
#  sy_flutter_wechat: ^0.2.2
#  fluwx: ^3.4.2
  # 第三方登录 google firebase等
#  firebase_analytics: ^5.0.2
#  firebase_core: ^0.4.0+9
#  data_finder: ^0.0.7
  #  # google_sign_in: ^5.0.1
  #    firebase_auth: ^1.0.1
  #  google_sign_in: ^4.5.1
  #  google_sign_in_web: ^0.9.1
  #  flutter_facebook_login: ^3.0.0
  # shared_preferences: ^2.0.5
  #动态加载条加载页面
  shimmer: ^2.0.0
  path_provider: ^2.0.1
  convex_bottom_bar: ^3.0.0
  marquee_flutter: ^0.1.2  #跑马灯文字
#  photo: ^0.4.8 #相册选择
  flutter_share_me: ^0.10.0
  share: ^2.0.1
  file_utils: ^0.1.3
    #打开文件
  open_file: ^2.0.1+2
  popup_menu : ^1.0.5
  #选取多张图片
  wechat_assets_picker: ^5.5.2
  extended_image: ^4.0.0
  flutter_staggered_grid_view: "^0.3.2" #瀑布流错开效果
  top_snackbar_flutter: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  scrollable_list_tabview: ^0.1.6
#  achievement_view: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/state/
    - assets/images/login/
    - assets/images/me/
    - assets/images/search/
    - assets/images/personnel/
    - assets/images/product/
    - assets/images/company/
    - assets/images/use_icon/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: PingFang
    #   fonts:
    #     - asset: assets/fonts/PingFang-Thin.ttf
    - family: iconfontFonts
      fonts:
        - asset: assets/fonts/Iconfont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true